controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

exercises_by_muscle_group:
    path: '/muscle-group/{muscleGroupName}'
    controller: 'App\Controller\ExerciseController::exercisesByMuscleGroup'